const CategoryType = {
    FICTION: 'Fiction',
    MYSTERY_THRILLER_CRIME: 'Mystery/Thriller/Crime',
    ROMANCE: 'Romance',
    FANTASY: 'Fantasy',
    SCIENCE_FICTION: 'Science Fiction',
    HORROR: 'Horror',
    HISTORICAL_FICTION: 'Historical Fiction',
    ADVENTURE: 'Adventure',
    DYSTOPIAN: 'Dystopian',
    YOUNG_ADULT: 'Young Adult (YA)',
    CHILDRENS_BOOKS: "Children's Books",
    GRAPHIC_NOVELS_COMICS: 'Graphic Novels/Comics',
    POETRY: 'Poetry',
    NON_FICTION: 'Non-Fiction',
    BIOGRAPHY_AUTObIOGRAPHY_MEMOIR: 'Biography/Autobiography/Memoir',
    SELF_HELP_PERSONAL_DEVELOPMENT: 'Self-Help/Personal Development',
    PSYCHOLOGY: 'Psychology',
    PHILOSOPHY: 'Philosophy',
    SCIENCE_NATURE: 'Science/Nature',
    HISTORY: 'History',
    POLITICS_GOVERNMENT: 'Politics/Government',
    RELIGION_SPIRITUALITY: 'Religion/Spirituality',
    TRAVEL: 'Travel',
    COOKBOOKS_FOOD: 'Cookbooks/Food',
    HEALTH_FITNESS: 'Health/Fitness',
    ART_PHOTOGRAPHY: 'Art/Photography',
    MUSIC: 'Music',
    BUSINESS_ENTREPRENEURSHIP: 'Business/Entrepreneurship',
    ECONOMICS: 'Economics',
    TECHNOLOGY_COMPUTER_SCIENCE: 'Technology/Computer Science',
    PARENTING_FAMILY: 'Parenting/Family',
    RELATIONSHIPS: 'Relationships',
    SPORTS: 'Sports',
    TRUE_CRIME: 'True Crime',
    ESSAYS: 'Essays',
    ANTHOLOGIES: 'Anthologies',
    REFERENCE_GUIDES: 'Reference/Guides',
    EDUCATION: 'Education',
    ENVIRONMENTAL_CLIMATE: 'Environmental/Climate',
    LGBTQ_LITERATURE: 'LGBTQ+ Literature',
    CULTURAL_SOCIAL_ISSUES: 'Cultural/Social Issues',
    PHILOSOPHY_OF_LIFE: 'Philosophy of Life',
    LITERARY_CRITICISM: 'Essays/Critiques on Literature',
    SHORT_STORY_COLLECTIONS: 'Anthologies/Short Story Collections',
    CLASSIC_LITERATURE: 'Classic Literature',
};

module.exports = CategoryType;